"""Value objects of the ``reports`` bounded context.

A report is one raw observation from one person or organisation (``AGENTS.md`` §7).
These types describe what the reporter said: where and when they observed something,
how precise their position is, what they think it was and in what words. Nothing here
is trusted; triage flags are suggestions for a moderator and never change a report.

Two codes mirror another module's format instead of importing it, because a domain
layer may import only the standard library, Pydantic, ``geojson-pydantic`` and the
shared kernel (``AGENTS.md`` §2.1): ``GuessedHazardCode`` mirrors
``hazards.HazardCode`` and ``PlaceHint`` mirrors ``geography.PlaceCode``. A unit test
keeps each pattern identical to its original, and the application layer checks through
the other module's facade that the code actually exists.

Patterns: Value Object.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated, Final, Literal, Self

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

from yakhnama.shared_kernel.ids import EntityId
from yakhnama.shared_kernel.text import safe_text
from yakhnama.shared_kernel.value_objects import (
    Confidence,
    Coordinates,
    DateWithPrecision,
    LanguageCode,
    Measurement,
)

REPORT_AGGREGATE_TYPE: Final = "report"

ClientReportId = EntityId
"""The report's identity, generated by the reporting client as a UUIDv7.

Offline clients create the id when the observation is written down, so a report sent
twice (after a lost response or a reconnect) carries the same id and ``SubmitReport``
can be idempotent on it. The timestamp embedded in the id is set by the client's clock
and is never used as the observation or submission time (ADR 0006).
"""

GPS_ACCURACY_MAX_METRES: Final = 10_000.0
"""Largest accepted horizontal accuracy radius; a fix worse than 10 km is not a fix."""


class GpsAccuracy(Measurement):
    """Horizontal accuracy radius of a reporter's position fix, in metres.

    The radius the device reports (for example ``Location.getAccuracy`` on Android
    or ``horizontalAccuracy`` on iOS): the true position lies within it with the
    device's own, usually 68 %, confidence. Zero is allowed because some devices
    report it for a manually placed pin.

    Implements: Value Object.

    Attributes:
        value: Radius from 0 to ``GPS_ACCURACY_MAX_METRES``.
        unit: Always ``"metre"``.
    """

    value: float = Field(ge=0.0, le=GPS_ACCURACY_MAX_METRES, allow_inf_nan=False)
    unit: Literal["metre"] = "metre"

    @classmethod
    def metres(cls, value: float) -> Self:
        """Build an accuracy from a radius in metres.

        Args:
            value: The radius, from 0 to ``GPS_ACCURACY_MAX_METRES``.

        Returns:
            The accuracy.

        Raises:
            pydantic.ValidationError: If ``value`` is negative, too large or not
                finite.
        """
        return cls(value=value)


class ObservationPoint(BaseModel):
    """Where the reporter says the observation was made.

    This is the reporter's own position (private, stored exact); public payloads
    round it to ``public_coordinate_decimals`` and a place is never created from it
    (Phase 3 plan §2).

    Implements: Value Object.

    Attributes:
        coordinates: WGS84 position, longitude first.
        accuracy: The device's accuracy radius, or ``None`` when unknown (a pin
            placed by hand on a map, or a device that does not say).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    coordinates: Coordinates
    accuracy: GpsAccuracy | None = None


class ReportStatus(StrEnum):
    """Where a report is in its own lifecycle (not its verification).

    Verification is a separate state machine in the ``verification`` module; this
    status only says whether the report is being written, is the current revision,
    was replaced by a revision or was taken back by its reporter.

    Implements: Value Object.
    """

    DRAFT = "draft"
    SUBMITTED = "submitted"
    SUPERSEDED = "superseded"
    WITHDRAWN = "withdrawn"


GuestImageType = Literal["image/jpeg", "image/png", "image/webp"]
"""The media types a guest may upload (``guest_submissions.GUEST_IMAGE_TYPES``)."""


class ReportChannel(StrEnum):
    """How a report reached the platform (ADR 0019).

    - ``account``: the observer submitted it with their own account;
    - ``assisted``: someone with an account entered it for a person without
      one, and recorded that person's consent;
    - ``guest``: a person without an account submitted it after a proof-of-work
      check (ADR 0020).

    Every revision keeps the channel of the report it corrects. Moderators read
    the ``guest`` channel as a queue of its own.

    Implements: Value Object.
    """

    ACCOUNT = "account"
    GUEST = "guest"
    ASSISTED = "assisted"


class ConsentMethod(StrEnum):
    """How the assisted person gave consent to the report being entered.

    Implements: Value Object.
    """

    VERBAL = "verbal"
    WRITTEN = "written"


CONSENT_STATEMENT_VERSION_PATTERN: Final = r"^[a-z0-9][a-z0-9._-]{0,31}$"
ConsentStatementVersion = Annotated[
    str, StringConstraints(pattern=CONSENT_STATEMENT_VERSION_PATTERN)
]
"""Version of the consent statement read to or by the assisted person.

The statement itself lives with the client that shows it (the web portal keeps it
in its message catalogues); the report stores only which version was used, such as
``2026-10-05`` or ``v1``.
"""

ASSISTANCE_NOTE_MAX_LENGTH: Final = 500
AssistanceNote = Annotated[
    str, *safe_text(ASSISTANCE_NOTE_MAX_LENGTH, allow_line_breaks=True)
]
"""A private note by the assisting person, 1 to 500 characters of safe text.

Shown only to the person who entered the report and to moderators; never in a
listing, an event or a log.
"""


class AssistedSubmission(BaseModel):
    """What an assisted report records about the assistance and the consent.

    It never identifies the assisted person: no name, contact or account. The
    person who entered the report is the report's reporter.

    Implements: Value Object.

    Attributes:
        consent_method: How the assisted person consented.
        consent_statement_version: Which consent statement they agreed to.
        note: A private note by the assisting person, if any.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    consent_method: ConsentMethod
    consent_statement_version: ConsentStatementVersion
    note: AssistanceNote | None = None


REVISION_NUMBER_MAX: Final = 1000
"""Technical bound on revisions per report chain, far above any real correction."""

RevisionNumber = Annotated[int, Field(ge=1, le=REVISION_NUMBER_MAX)]
"""Position of a report in its revision chain: 1 for the original, +1 per revision."""

REPORT_VERSION_MAX: Final = 2**31 - 1
ReportVersion = Annotated[int, Field(ge=1, le=REPORT_VERSION_MAX)]
"""Optimistic-concurrency version: 1 when created, +1 per change with an effect.

The bound is the largest signed 32-bit integer so it fits a PostgreSQL ``integer``.
"""

# Mirrors ``yakhnama.modules.hazards.domain.value_objects.HazardCode``; see the module
# docstring for why it is copied and how the copy is kept identical.
HAZARD_CODE_PATTERN: Final = r"^[a-z][a-z0-9_]{1,63}$"
GuessedHazardCode = Annotated[str, StringConstraints(pattern=HAZARD_CODE_PATTERN)]
"""Code of the hazard type the reporter believes they saw, such as ``"glof"``."""

# Mirrors ``yakhnama.modules.geography.domain.value_objects.PLACE_CODE_PATTERN``.
PLACE_CODE_PATTERN: Final = r"^[a-z0-9][a-z0-9_.-]{1,63}$"
PlaceHint = Annotated[str, StringConstraints(pattern=PLACE_CODE_PATTERN)]
"""Code of the place the reporter picked, such as ``pk.gb.hunza``; only a hint."""


class HazardGuess(BaseModel):
    """What the reporter thinks they observed, and how sure they are.

    A guess, never a classification: moderators decide the hazard type of the
    canonical event.

    Implements: Value Object.

    Attributes:
        hazard_code: Code of a hazard type in the taxonomy.
        confidence: The reporter's own confidence in the guess.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    hazard_code: GuessedHazardCode
    confidence: Confidence


DESCRIPTION_MAX_LENGTH: Final = 4000
Description = Annotated[str, *safe_text(DESCRIPTION_MAX_LENGTH, allow_line_breaks=True)]
"""What the reporter saw, in their own words: safe text, 1 to 4000 characters.

Line breaks are kept (long-form text); other control characters, lone surrogates and
bidirectional overrides are refused (``yakhnama.shared_kernel.text``).
"""

REASON_MAX_LENGTH: Final = 500
WithdrawalReason = Annotated[str, *safe_text(REASON_MAX_LENGTH)]
"""Why the reporter took a report back: single-line safe text, 1 to 500 characters."""

TriageDetail = Annotated[str, *safe_text(REASON_MAX_LENGTH)]
"""A moderator-facing explanation of a triage flag, 1 to 500 characters.

Written by the triage rules, never copied from the report: it names what was found
(``"phone number"``) but never repeats the text or the coordinates.
"""

MEDIA_PER_REPORT_MAX: Final = 20
"""Most media assets one report may reference (**proposed**, Q-R7)."""

TriageFlagKind = Literal[
    "exif_implausible", "duplicate_suspected", "pii_detected", "spam_suspected"
]
"""What a triage rule suspects about a report."""

TRIAGE_FLAGS_MAX: Final = 32


class TriageFlag(BaseModel):
    """One suspicion raised by a triage rule, for a moderator to confirm or dismiss.

    Implements: Value Object.

    Attributes:
        kind: What is suspected.
        detail: Why, in words a moderator can act on; no personal data.
        confidence: How strongly the rule's signal supports the suspicion.
        related_report_id: The other report involved (for ``duplicate_suspected``),
            or ``None``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    kind: TriageFlagKind
    detail: TriageDetail
    confidence: Confidence
    related_report_id: EntityId | None = None


class TriageResult(BaseModel):
    """The outcome of running the triage chain over one report.

    An empty ``flags`` tuple means no rule raised a suspicion; it does not mean the
    report is verified.

    Implements: Value Object.

    Attributes:
        flags: Flags in the order the rules ran.
        evaluated_at: When the chain ran, UTC.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    flags: tuple[TriageFlag, ...] = Field(default=(), max_length=TRIAGE_FLAGS_MAX)
    evaluated_at: AwareDatetime

    @field_validator("evaluated_at", mode="after")
    @classmethod
    def _normalise_to_utc(cls, value: datetime) -> datetime:
        return value.astimezone(UTC)

    @property
    def has_flags(self) -> bool:
        """Tell whether any rule raised a suspicion.

        Returns:
            ``True`` if ``flags`` is not empty.
        """
        return bool(self.flags)

    @property
    def kinds(self) -> tuple[TriageFlagKind, ...]:
        """Return the kind of every flag, in order.

        Returns:
            One kind per flag; a kind repeats if several flags share it.
        """
        return tuple(flag.kind for flag in self.flags)


class ReportContent(BaseModel):
    """Everything the reporter states in one revision of a report.

    A revision replaces the whole content, so clearing a guess or a place hint is as
    explicit as setting one.

    Implements: Value Object.

    Attributes:
        observed_at: When the reporter observed it, with its precision.
        observation: Where the reporter was.
        description: What they saw, in their words.
        original_language: The language and script ``description`` is written in.
        hazard_guess: What they think it was, or ``None``.
        place_hint: A place they picked, or ``None``.
        media_ids: Media assets attached, unique, in the reporter's order.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    observed_at: DateWithPrecision
    observation: ObservationPoint
    description: Description
    original_language: LanguageCode
    hazard_guess: HazardGuess | None = None
    place_hint: PlaceHint | None = None
    media_ids: tuple[EntityId, ...] = Field(default=(), max_length=MEDIA_PER_REPORT_MAX)

    @model_validator(mode="after")
    def _check_unique_media(self) -> Self:
        if len(set(self.media_ids)) != len(self.media_ids):
            message = "a media asset may be attached to a report only once"
            raise ValueError(message)
        return self


class ReportAttribution(BaseModel):
    """Who a report comes from: reporter, organisation, source and channel.

    Kept together because every revision of a report inherits all of them
    unchanged. ``reporter_id`` is the principal accountable for the report: the
    user who entered it for the ``account`` and ``assisted`` channels, and the
    guest submission that carried it for the ``guest`` channel (ADR 0020). Both
    kinds of id come from the platform's one UUIDv7 generator, so a guest
    submission's id never equals a user's and "the reporter" policies never match
    a guest report.

    Implements: Value Object.

    Attributes:
        reporter_id: The reporting user, or the guest submission.
        organization_id: The organisation the user reported for, or ``None``.
        source_id: The ``provenance`` source record the report is attributed to.
        channel: How the report reached the platform.
        assisted: The assistance and consent record, exactly for ``assisted``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    reporter_id: EntityId
    organization_id: EntityId | None = None
    source_id: EntityId
    channel: ReportChannel = ReportChannel.ACCOUNT
    assisted: AssistedSubmission | None = None

    @model_validator(mode="after")
    def _check_channel(self) -> Self:
        check_channel_fields(self.channel, self.assisted, self.organization_id)
        return self


def check_channel_fields(
    channel: ReportChannel,
    assisted: AssistedSubmission | None,
    organization_id: EntityId | None,
) -> None:
    """Check that the channel and its fields agree.

    Args:
        channel: The report's channel.
        assisted: Its assistance record, if any.
        organization_id: The organisation it was reported for, if any.

    Raises:
        ValueError: If ``assisted`` is set for another channel than ``assisted``
            or missing for it, or a guest report names an organisation.
    """
    if (assisted is None) == (channel is ReportChannel.ASSISTED):
        message = "assisted must be set exactly for an assisted report"
        raise ValueError(message)
    if channel is ReportChannel.GUEST and organization_id is not None:
        message = "a guest report is never reported for an organisation"
        raise ValueError(message)
