"""Public facade of the ``reports`` module.

Other modules, the API and the composition root import only this file: the
commands, queries, DTOs and handlers, the ports the composition root binds
(including the three answered by other modules), the triage value types an adapter
builds (``PhotoEvidence``, ``ReportSummaryForTriage``), the task name the worker
routes, and the guest submission use cases, DTOs, ports and errors (ADR 0020).

Patterns: Facade.
"""

from yakhnama.modules.reports.application.authorisation import (
    assisted_submit_policy,
    exact_view_policy,
    is_moderator,
    reporter_policy,
    require_user,
    rounded_view_policy,
    submit_policy,
    triage_view_policy,
)
from yakhnama.modules.reports.application.commands import (
    CompleteGuestMediaUpload,
    IssueGuestChallenge,
    OpenGuestSubmission,
    PurgeGuestRecords,
    RequestGuestMediaUpload,
    ReviseReport,
    RunTriage,
    SubmitGuestReport,
    SubmitReport,
    WithdrawReport,
)
from yakhnama.modules.reports.application.dto import (
    GuestChallengeGrant,
    GuestMediaAsset,
    GuestPurgeOutcome,
    GuestReportReceipt,
    GuestSubmissionGrant,
    GuestSubmissionWindow,
    ReportDetail,
    ReportRecord,
    ReportSummary,
)
from yakhnama.modules.reports.application.guest_handlers import (
    GUEST_SOURCE_CITATION,
    GUEST_SOURCE_TITLE,
    CompleteGuestMediaUploadHandler,
    GuestHandlerDependencies,
    IssueGuestChallengeHandler,
    OpenGuestSubmissionHandler,
    PurgeGuestRecordsHandler,
    RequestGuestMediaUploadHandler,
    SubmitGuestReportHandler,
)
from yakhnama.modules.reports.application.handlers import (
    ASSISTED_CITIZEN_SOURCE_CITATION,
    ASSISTED_CITIZEN_SOURCE_TITLE,
    ASSISTED_ORGANISATION_SOURCE_CITATION,
    ASSISTED_ORGANISATION_SOURCE_TITLE,
    CITIZEN_SOURCE_CITATION,
    CITIZEN_SOURCE_TITLE,
    ORGANISATION_SOURCE_CITATION,
    ORGANISATION_SOURCE_TITLE,
    ReviseReportHandler,
    RunTriageHandler,
    SubmitReportHandler,
    WithdrawReportHandler,
)
from yakhnama.modules.reports.application.ports import (
    RUN_TRIAGE_TASK,
    GuestChallengeSigner,
    GuestMediaGateway,
    GuestSecretGenerator,
    GuestSubmissionRepository,
    MediaOwnershipChecker,
    NearbyReportsFinder,
    PhotoEvidenceProvider,
    ReportQueryService,
    ReportRepository,
    ReportsUnitOfWork,
    ReportsUnitOfWorkFactory,
    SpentChallengeRepository,
)
from yakhnama.modules.reports.application.queries import (
    FindNearbyReports,
    GetReport,
    ListReports,
)
from yakhnama.modules.reports.application.query_services import (
    AuthorisedReportQueryService,
)
from yakhnama.modules.reports.application.specifications import (
    ReportChannelSpecification,
    ReportHazardCodeSpecification,
    ReportInBoundingBoxSpecification,
    ReportObservedFromSpecification,
    ReportObservedToSpecification,
    ReportReporterSpecification,
    ReportStatusSpecification,
)
from yakhnama.modules.reports.domain.errors import (
    GuestCapabilityExpiredError,
    GuestCapabilityInvalidError,
    GuestChallengeExpiredError,
    GuestChallengeInvalidError,
    GuestChallengeSpentError,
    GuestMediaLimitError,
    GuestMediaNotFoundError,
    GuestProofInvalidError,
    GuestSubmissionClosedError,
    GuestSubmissionLimitError,
    ReportImmutableError,
    ReportNotFoundError,
    ReportRevisionUnchangedError,
    ReportWithdrawnError,
)
from yakhnama.modules.reports.domain.guest_submissions import (
    GUEST_MEDIA_MAX,
    GuestCap,
    GuestChallenge,
    GuestSubmission,
    GuestSubmissionLimits,
)
from yakhnama.modules.reports.domain.triage import (
    PhotoEvidence,
    ReportSummaryForTriage,
)
from yakhnama.modules.reports.domain.value_objects import (
    AssistedSubmission,
    ConsentMethod,
    GuestImageType,
    HazardGuess,
    ObservationPoint,
    ReportChannel,
    ReportContent,
    ReportStatus,
    TriageFlag,
    TriageResult,
)

__all__ = [
    "ASSISTED_CITIZEN_SOURCE_CITATION",
    "ASSISTED_CITIZEN_SOURCE_TITLE",
    "ASSISTED_ORGANISATION_SOURCE_CITATION",
    "ASSISTED_ORGANISATION_SOURCE_TITLE",
    "CITIZEN_SOURCE_CITATION",
    "CITIZEN_SOURCE_TITLE",
    "GUEST_MEDIA_MAX",
    "GUEST_SOURCE_CITATION",
    "GUEST_SOURCE_TITLE",
    "ORGANISATION_SOURCE_CITATION",
    "ORGANISATION_SOURCE_TITLE",
    "RUN_TRIAGE_TASK",
    "AssistedSubmission",
    "AuthorisedReportQueryService",
    "CompleteGuestMediaUpload",
    "CompleteGuestMediaUploadHandler",
    "ConsentMethod",
    "FindNearbyReports",
    "GetReport",
    "GuestCap",
    "GuestCapabilityExpiredError",
    "GuestCapabilityInvalidError",
    "GuestChallenge",
    "GuestChallengeExpiredError",
    "GuestChallengeGrant",
    "GuestChallengeInvalidError",
    "GuestChallengeSigner",
    "GuestChallengeSpentError",
    "GuestHandlerDependencies",
    "GuestImageType",
    "GuestMediaAsset",
    "GuestMediaGateway",
    "GuestMediaLimitError",
    "GuestMediaNotFoundError",
    "GuestProofInvalidError",
    "GuestPurgeOutcome",
    "GuestReportReceipt",
    "GuestSecretGenerator",
    "GuestSubmission",
    "GuestSubmissionClosedError",
    "GuestSubmissionGrant",
    "GuestSubmissionLimitError",
    "GuestSubmissionLimits",
    "GuestSubmissionRepository",
    "GuestSubmissionWindow",
    "HazardGuess",
    "IssueGuestChallenge",
    "IssueGuestChallengeHandler",
    "ListReports",
    "MediaOwnershipChecker",
    "NearbyReportsFinder",
    "ObservationPoint",
    "OpenGuestSubmission",
    "OpenGuestSubmissionHandler",
    "PhotoEvidence",
    "PhotoEvidenceProvider",
    "PurgeGuestRecords",
    "PurgeGuestRecordsHandler",
    "ReportChannel",
    "ReportChannelSpecification",
    "ReportContent",
    "ReportDetail",
    "ReportHazardCodeSpecification",
    "ReportImmutableError",
    "ReportInBoundingBoxSpecification",
    "ReportNotFoundError",
    "ReportObservedFromSpecification",
    "ReportObservedToSpecification",
    "ReportQueryService",
    "ReportRecord",
    "ReportReporterSpecification",
    "ReportRepository",
    "ReportRevisionUnchangedError",
    "ReportStatus",
    "ReportStatusSpecification",
    "ReportSummary",
    "ReportSummaryForTriage",
    "ReportWithdrawnError",
    "ReportsUnitOfWork",
    "ReportsUnitOfWorkFactory",
    "RequestGuestMediaUpload",
    "RequestGuestMediaUploadHandler",
    "ReviseReport",
    "ReviseReportHandler",
    "RunTriage",
    "RunTriageHandler",
    "SpentChallengeRepository",
    "SubmitGuestReport",
    "SubmitGuestReportHandler",
    "SubmitReport",
    "SubmitReportHandler",
    "TriageFlag",
    "TriageResult",
    "WithdrawReport",
    "WithdrawReportHandler",
    "assisted_submit_policy",
    "exact_view_policy",
    "is_moderator",
    "reporter_policy",
    "require_user",
    "rounded_view_policy",
    "submit_policy",
    "triage_view_policy",
]
