"""Alembic migration round trips, drift check and history shape on real PostGIS.

Alembic runs in-process through ``alembic.command`` with the container URL passed as
``-x database_url=...``, exactly as a developer would pass it on the command line.
The tests are plain ``def`` functions on purpose: ``migrations/env.py`` drives its own
event loop with ``asyncio.run``, which cannot start inside a running pytest-asyncio
loop.

Every test leaves the session database empty (no application tables, no
``alembic_version``) because the platform integration tests create the outbox table
themselves and would collide with a migrated schema.
"""

import asyncio
import io
from argparse import Namespace
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from pydantic import BaseModel, ConfigDict
from sqlalchemy import Connection, inspect, text
from sqlalchemy.exc import DBAPIError, IntegrityError
from sqlalchemy.ext.asyncio import create_async_engine

pytestmark = pytest.mark.integration

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[3]
ALEMBIC_INI: Final = REPOSITORY_ROOT / "alembic.ini"

VERSION_TABLE: Final = "alembic_version"
# Tables the PostGIS image creates in the public schema; they are not ours.
POSTGIS_TABLES: Final = frozenset({"spatial_ref_sys"})
APPLICATION_TABLES_AT_HEAD: Final = frozenset(
    {
        "outbox_messages",
        "places",
        "place_names",
        "district_edge_sets",
        "district_centroids",
        "district_edges",
        "hazard_types",
        "impact_metrics",
        "users",
        "organizations",
        "memberships",
        "idempotency_keys",
        "sources",
        "audit_entries",
        "reports",
        "media_assets",
        "events",
        "event_relations",
        "event_report_links",
        "verification_cases",
        "infrastructure_assets",
        "impact_claims",
        "damage_records",
        "datasets",
        "dataset_versions",
        "ingestion_runs",
        "observations",
        "raster_assets",
        "export_jobs",
        "import_jobs",
        "guest_submissions",
        "guest_challenges",
        "report_reviews",
        "report_review_marks",
    }
)
EXTENSIONS: Final = frozenset({"postgis", "pg_trgm", "unaccent"})


def _read_public_tables(connection: Connection) -> set[str]:
    """Return the table names in the public schema."""
    return set(inspect(connection).get_table_names(schema="public"))


async def _fetch_public_tables(database_url: str) -> set[str]:
    """Connect once and list the public tables."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            return await connection.run_sync(_read_public_tables)
    finally:
        await engine.dispose()


async def _fetch_extensions(database_url: str) -> set[str]:
    """Connect once and list the installed extensions."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            result = await connection.execute(text("SELECT extname FROM pg_extension"))
            return set(result.scalars().all())
    finally:
        await engine.dispose()


async def _execute(database_url: str, statement: str) -> None:
    """Run one fixed DDL statement in its own transaction."""
    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as connection:
            await connection.execute(text(statement))
    finally:
        await engine.dispose()


def _application_tables(database_url: str) -> set[str]:
    """Return every public table that is neither PostGIS's nor Alembic's."""
    tables = asyncio.run(_fetch_public_tables(database_url))
    return tables - POSTGIS_TABLES - {VERSION_TABLE}


def _build_config(
    database_url: str, output_buffer: io.StringIO | None = None
) -> Config:
    """Return an Alembic config for ``alembic.ini`` aimed at ``database_url``."""
    config = Config(
        ALEMBIC_INI,
        cmd_opts=Namespace(x=[f"database_url={database_url}"]),
        output_buffer=output_buffer,
    )
    # env.py would otherwise call fileConfig and replace pytest's log handlers.
    config.attributes["configure_logger"] = False
    return config


@pytest.fixture
def alembic_config(postgis_url: str) -> Iterator[Config]:
    """Yield a config on the empty session database and empty it again afterwards."""
    config = _build_config(postgis_url)

    yield config

    command.downgrade(config, "base")
    # downgrade base only empties the version table; drop it so the database is
    # exactly as empty as the platform tests expect.
    asyncio.run(_execute(postgis_url, f"DROP TABLE IF EXISTS {VERSION_TABLE}"))


def test_migrations_upgrade_head_downgrade_base_leaves_empty_schema(
    alembic_config: Config, postgis_url: str
) -> None:
    assert _application_tables(postgis_url) == set()

    command.upgrade(alembic_config, "head")
    tables_at_head = _application_tables(postgis_url)
    extensions_at_head = asyncio.run(_fetch_extensions(postgis_url))
    command.downgrade(alembic_config, "base")
    tables_at_base = _application_tables(postgis_url)

    assert tables_at_head == APPLICATION_TABLES_AT_HEAD
    assert extensions_at_head >= EXTENSIONS
    assert tables_at_base == set()


def test_migrations_upgrade_twice_is_idempotent_after_downgrade(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    command.upgrade(alembic_config, "head")

    assert _application_tables(postgis_url) == APPLICATION_TABLES_AT_HEAD


def test_alembic_check_reports_no_drift_at_head(alembic_config: Config) -> None:
    command.upgrade(alembic_config, "head")

    # Raises AutogenerateDiffsDetected if the models and the migrations disagree.
    command.check(alembic_config)


def test_alembic_check_with_column_altered_by_hand_reports_drift(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "head")
    # A change downgrade still undoes (it drops the whole table), so the fixture's
    # teardown keeps working.
    asyncio.run(
        _execute(
            postgis_url,
            "ALTER TABLE outbox_messages ALTER COLUMN last_error SET NOT NULL",
        )
    )

    with pytest.raises(AutogenerateDiffsDetected, match="last_error"):
        command.check(alembic_config)


def test_migrations_offline_mode_renders_outbox_sql_without_connecting(
    postgis_url: str,
) -> None:
    output = io.StringIO()
    config = _build_config(postgis_url, output_buffer=output)

    command.upgrade(config, "head", sql=True)

    rendered = output.getvalue()
    assert "CREATE EXTENSION IF NOT EXISTS postgis" in rendered
    assert "CREATE TABLE outbox_messages" in rendered
    assert _application_tables(postgis_url) == set()


def _read_observations_layout(
    connection: Connection,
) -> tuple[list[str], list[object]]:
    """Return the primary key columns and foreign keys of ``observations``."""
    inspector = inspect(connection)
    primary_key = inspector.get_pk_constraint("observations")["constrained_columns"]
    return list(primary_key), list(inspector.get_foreign_keys("observations"))


async def _fetch_observations_layout(
    database_url: str,
) -> tuple[list[str], list[object]]:
    """Connect once and read the ``observations`` key layout."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            return await connection.run_sync(_read_observations_layout)
    finally:
        await engine.dispose()


def test_migrations_observations_key_is_time_first_without_foreign_keys(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "head")

    primary_key, foreign_keys = asyncio.run(_fetch_observations_layout(postgis_url))

    # TimescaleDB hypertables need the time column in every unique index and cannot
    # be blocked by foreign keys; this is what keeps the table hypertable-ready.
    assert primary_key == [
        "observed_at",
        "dataset_version_id",
        "variable_code",
        "site_ref",
    ]
    assert foreign_keys == []


def test_migration_history_is_linear() -> None:
    script = ScriptDirectory.from_config(Config(ALEMBIC_INI))

    revisions = list(script.walk_revisions())

    assert len(script.get_heads()) == 1
    assert len(script.get_bases()) == 1
    assert all(
        revision.down_revision is None or isinstance(revision.down_revision, str)
        for revision in revisions
    )
    assert all(not revision.branch_labels for revision in revisions)


_EXPORT_ROW: Final = (
    "INSERT INTO export_jobs (id, requested_by, dataset, format, filters, status, "
    "sidecar, requested_at, version) VALUES ('{id}', "
    "'01890000-0000-7000-8000-0000000000aa', '{dataset}', 'csv', '{{}}', "
    "'{status}', {sidecar}, '2026-09-01T00:00:00Z', 1)"
)
_REPORTS_JOB: Final = "01890000-0000-7000-8000-0000000000a1"
_EVENTS_JOB: Final = "01890000-0000-7000-8000-0000000000a2"


async def _fetch_visibility(database_url: str) -> dict[str, tuple[object, ...]]:
    """Return ``id -> (visibility column, sidecar's visibility key)`` per export."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            has_column = "visibility" in {
                column["name"]
                for column in await connection.run_sync(
                    lambda sync: inspect(sync).get_columns("export_jobs")
                )
            }
            column = "visibility" if has_column else "NULL"
            result = await connection.execute(
                text(
                    f"SELECT id::text, {column}, sidecar ->> 'visibility', "  # noqa: S608  # reason: the column name is one of two literals above
                    "sidecar ? 'visibility' FROM export_jobs"
                )
            )
            return {row[0]: tuple(row[1:]) for row in result}
    finally:
        await engine.dispose()


def test_migration_0018_labels_reports_exports_and_sidecars_reversibly(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0017")
    reports = _EXPORT_ROW.format(
        id=_REPORTS_JOB,
        dataset="reports",
        status="completed",
        sidecar="""'{"row_count": 1}'""",
    )
    events = _EXPORT_ROW.format(
        id=_EVENTS_JOB, dataset="events", status="queued", sidecar="NULL"
    )
    asyncio.run(_execute(postgis_url, reports))
    asyncio.run(_execute(postgis_url, events))

    command.upgrade(alembic_config, "0018")
    upgraded = asyncio.run(_fetch_visibility(postgis_url))
    command.downgrade(alembic_config, "0017")
    downgraded = asyncio.run(_fetch_visibility(postgis_url))
    asyncio.run(_execute(postgis_url, "DELETE FROM export_jobs"))

    assert upgraded == {
        _REPORTS_JOB: ("moderation", "moderation", True),
        _EVENTS_JOB: ("public", None, None),
    }
    assert downgraded[_REPORTS_JOB] == (None, None, False)


_REPORT_ROW: Final = (
    "INSERT INTO reports (id, reporter_id, source_id, observed_at, "
    "observed_at_precision, observation, description, original_language, media_ids, "
    "status, revision, submitted_at, version, created_at, updated_at) VALUES "
    "('01890000-0000-7000-8000-0000000000b1', '01890000-0000-7000-8000-0000000000b2', "
    "'01890000-0000-7000-8000-0000000000b3', '2026-09-01T00:00:00Z', 'exact', "
    "ST_SetSRID(ST_MakePoint(74.3, 35.9), 4326), 'Synthetic test report.', 'en', "
    "'[]', 'submitted', 1, '2026-09-01T00:00:00Z', 1, '2026-09-01T00:00:00Z', "
    "'2026-09-01T00:00:00Z')"
)


async def _fetch_report_channels(database_url: str) -> list[object]:
    """Return the ``channel`` of every report, or ``[]`` without the column."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            columns = {
                column["name"]
                for column in await connection.run_sync(
                    lambda sync: inspect(sync).get_columns("reports")
                )
            }
            if "channel" not in columns:
                return []
            result = await connection.execute(text("SELECT channel FROM reports"))
            return list(result.scalars().all())
    finally:
        await engine.dispose()


def test_migration_0019_labels_existing_reports_account_reversibly(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0018")
    asyncio.run(_execute(postgis_url, _REPORT_ROW))

    command.upgrade(alembic_config, "0019")
    upgraded = asyncio.run(_fetch_report_channels(postgis_url))
    tables = _application_tables(postgis_url)
    command.downgrade(alembic_config, "0018")
    downgraded = asyncio.run(_fetch_report_channels(postgis_url))
    downgraded_tables = _application_tables(postgis_url)
    asyncio.run(_execute(postgis_url, "DELETE FROM reports"))

    assert upgraded == ["account"]
    assert {"guest_submissions", "guest_challenges"} <= tables
    assert downgraded == []
    assert not {"guest_submissions", "guest_challenges"} & downgraded_tables


_FILED_GUEST_ROW: Final = (
    "INSERT INTO guest_submissions (id, capability_digest, expires_at, media_ids, "
    "report_id, reference, content_fingerprint, submitted_at, version, created_at, "
    "updated_at) VALUES ('01890000-0000-7000-8000-0000000000c1', "
    "'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', "
    "'2026-09-01T00:30:00Z', '[]', '01890000-0000-7000-8000-0000000000b1', "
    "'YK-ABCD-2345', "
    "'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', "
    "'2026-09-01T00:00:00Z', 2, '2026-09-01T00:00:00Z', '2026-09-01T00:00:00Z')"
)


async def _fetch_guest_sources(database_url: str) -> list[object]:
    """Return the ``source_id`` of every guest submission, or ``[]`` without it."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            columns = {
                column["name"]
                for column in await connection.run_sync(
                    lambda sync: inspect(sync).get_columns("guest_submissions")
                )
            }
            if "source_id" not in columns:
                return []
            result = await connection.execute(
                text("SELECT source_id::text FROM guest_submissions")
            )
            return list(result.scalars().all())
    finally:
        await engine.dispose()


def test_migrations_0021_to_0023_backfill_guest_sources_reversibly(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0020")
    asyncio.run(_execute(postgis_url, _REPORT_ROW))
    asyncio.run(_execute(postgis_url, "UPDATE reports SET channel = 'guest'"))
    asyncio.run(_execute(postgis_url, _FILED_GUEST_ROW))

    command.upgrade(alembic_config, "0023")
    upgraded = asyncio.run(_fetch_guest_sources(postgis_url))
    command.downgrade(alembic_config, "0020")
    downgraded = asyncio.run(_fetch_guest_sources(postgis_url))
    asyncio.run(_execute(postgis_url, "DELETE FROM guest_submissions"))
    asyncio.run(_execute(postgis_url, "DELETE FROM reports"))

    assert upgraded == ["01890000-0000-7000-8000-0000000000b3"]
    assert downgraded == []


@pytest.mark.parametrize(
    "statement",
    [
        (
            "UPDATE reports SET channel = 'guest', "
            "organization_id = '01890000-0000-7000-8000-0000000000d1'"
        ),
        (
            "UPDATE reports SET channel = 'assisted', "
            "assisted_consent_method = 'nodded', "
            "assisted_consent_statement_version = 'v1'"
        ),
        (
            "UPDATE reports SET channel = 'assisted', "
            "assisted_consent_method = 'verbal', "
            "assisted_consent_statement_version = 'Not A Version'"
        ),
    ],
)
def test_migration_0021_checks_refuse_what_the_domain_forbids(
    alembic_config: Config, postgis_url: str, statement: str
) -> None:
    # The row predates 0025's lineage column; 0025 backfills it on the way up.
    command.upgrade(alembic_config, "0024")
    asyncio.run(_execute(postgis_url, _REPORT_ROW))
    command.upgrade(alembic_config, "head")

    with pytest.raises(IntegrityError):
        asyncio.run(_execute(postgis_url, statement))

    asyncio.run(_execute(postgis_url, "DELETE FROM reports"))


_REVISION_ROW: Final = (
    "INSERT INTO reports (id, reporter_id, source_id, observed_at, "
    "observed_at_precision, observation, description, original_language, media_ids, "
    "status, revision, supersedes_id, submitted_at, version, created_at, updated_at) "
    "VALUES ('01890000-0000-7000-8000-0000000000e1', "
    "'01890000-0000-7000-8000-0000000000b2', '01890000-0000-7000-8000-0000000000b3', "
    "'2026-09-01T00:00:00Z', 'exact', ST_SetSRID(ST_MakePoint(74.3, 35.9), 4326), "
    "'Synthetic correction.', 'en', '[]', 'submitted', 2, "
    "'01890000-0000-7000-8000-0000000000b1', '2026-09-02T00:00:00Z', 1, "
    "'2026-09-02T00:00:00Z', '2026-09-02T00:00:00Z')"
)


async def _fetch_lineages(database_url: str) -> dict[str, str | None]:
    """Return the ``lineage_id`` of every report, or ``{}`` without the column."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            columns = {
                column["name"]
                for column in await connection.run_sync(
                    lambda sync: inspect(sync).get_columns("reports")
                )
            }
            if "lineage_id" not in columns:
                return {}
            result = await connection.execute(
                text("SELECT id::text, lineage_id::text FROM reports")
            )
            return {row[0]: row[1] for row in result}
    finally:
        await engine.dispose()


def test_migration_0025_backfills_lineages_and_creates_review_tables_reversibly(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0024")
    asyncio.run(_execute(postgis_url, _REPORT_ROW))
    asyncio.run(_execute(postgis_url, _REVISION_ROW))

    command.upgrade(alembic_config, "0025")
    upgraded = asyncio.run(_fetch_lineages(postgis_url))
    tables = _application_tables(postgis_url)
    command.downgrade(alembic_config, "0024")
    downgraded = asyncio.run(_fetch_lineages(postgis_url))
    downgraded_tables = _application_tables(postgis_url)
    asyncio.run(_execute(postgis_url, "DELETE FROM reports WHERE revision = 2"))
    asyncio.run(_execute(postgis_url, "DELETE FROM reports"))

    root = "01890000-0000-7000-8000-0000000000b1"
    assert upgraded == {root: root, "01890000-0000-7000-8000-0000000000e1": root}
    assert {"report_reviews", "report_review_marks"} <= tables
    assert downgraded == {}
    assert not {"report_reviews", "report_review_marks"} & downgraded_tables


_INSERT_REPORT: Final = (
    "INSERT INTO reports (id, reporter_id, source_id, observed_at, "
    "observed_at_precision, observation, description, original_language, media_ids, "
    "status, revision, supersedes_id, withdrawal_reason, channel, submitted_at, "
    "version, created_at, updated_at) VALUES (:id, "
    "'01890000-0000-7000-8000-0000000000b2', '01890000-0000-7000-8000-0000000000b3', "
    "'2026-09-01T00:00:00Z', 'exact', ST_SetSRID(ST_MakePoint(74.3, 35.9), 4326), "
    "'Synthetic.', 'en', '[]', :status, :revision, :supersedes_id, "
    ":withdrawal_reason, :channel, '2026-09-01T00:00:00Z', 1, "
    ":created_at, '2026-09-01T00:00:00Z')"
)
_INSERT_REPORT_WITH_LINEAGE: Final = (
    "INSERT INTO reports (id, reporter_id, source_id, observed_at, "
    "observed_at_precision, observation, description, original_language, media_ids, "
    "status, revision, supersedes_id, withdrawal_reason, channel, submitted_at, "
    "version, created_at, updated_at, lineage_id) VALUES (:id, "
    "'01890000-0000-7000-8000-0000000000b2', '01890000-0000-7000-8000-0000000000b3', "
    "'2026-09-01T00:00:00Z', 'exact', ST_SetSRID(ST_MakePoint(74.3, 35.9), 4326), "
    "'Synthetic.', 'en', '[]', :status, :revision, :supersedes_id, "
    ":withdrawal_reason, :channel, '2026-09-01T00:00:00Z', 1, "
    ":created_at, '2026-09-01T00:00:00Z', :lineage_id)"
)
_ROWS_CREATED: Final = datetime(2026, 9, 1, tzinfo=UTC)
_SUPERSEDE: Final = (
    "UPDATE reports SET status = 'superseded', superseded_by_id = :new WHERE id = :old"
)


class _Row(BaseModel):
    """One synthetic report row for the lineage migrations' tests.

    Implements: Value Object.

    Attributes:
        number: The last digits of its id.
        revision: Its revision number.
        supersedes: The number of the report it supersedes, if any.
        status: Its status.
        channel: How it arrived.
        lineage: The number of its lineage root, for schemas from 0025 on.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    number: int
    revision: int = 1
    supersedes: int | None = None
    status: str = "submitted"
    channel: str = "account"
    lineage: int | None = None


def _report_id(number: int) -> str:
    return f"01890000-0000-7000-8000-0000000{number:05d}"


async def _insert(database_url: str, *rows: _Row) -> None:
    """Insert synthetic reports in order, in one transaction."""
    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as connection:
            for row in rows:
                parameters: dict[str, object] = {
                    "id": _report_id(row.number),
                    "status": row.status,
                    "revision": row.revision,
                    "supersedes_id": (
                        None if row.supersedes is None else _report_id(row.supersedes)
                    ),
                    "withdrawal_reason": (
                        "Test withdrawal." if row.status == "withdrawn" else None
                    ),
                    "channel": row.channel,
                    "created_at": _ROWS_CREATED + timedelta(seconds=row.number),
                }
                statement = _INSERT_REPORT
                if row.lineage is not None:
                    parameters["lineage_id"] = _report_id(row.lineage)
                    statement = _INSERT_REPORT_WITH_LINEAGE
                await connection.execute(text(statement), parameters)
    finally:
        await engine.dispose()


async def _supersede(database_url: str, *pairs: tuple[int, int]) -> None:
    """Mark each ``(old, new)`` pair's old report superseded by the new one."""
    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as connection:
            for old, new in pairs:
                await connection.execute(
                    text(_SUPERSEDE), {"old": _report_id(old), "new": _report_id(new)}
                )
    finally:
        await engine.dispose()


def _delete_reports(database_url: str) -> None:
    """Delete every report, breaking the revision links first."""
    for statement in (
        "UPDATE reports SET superseded_by_id = NULL",
        "UPDATE reports SET supersedes_id = NULL",
        "DELETE FROM reports",
    ):
        asyncio.run(_execute(database_url, statement))


def test_migration_0025_backfills_long_chains_withdrawn_and_guest_lineages(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0024")
    asyncio.run(
        _insert(
            postgis_url,
            # A chain of four revisions: 1 <- 2 <- 3 <- 4, the first three superseded.
            _Row(number=1),
            _Row(number=2, revision=2, supersedes=1),
            _Row(number=3, revision=3, supersedes=2),
            _Row(number=4, revision=4, supersedes=3),
            # A correction later withdrawn by its reporter.
            _Row(number=11),
            _Row(number=12, revision=2, supersedes=11, status="withdrawn"),
            # A guest report, and a withdrawn first revision.
            _Row(number=21, channel="guest"),
            _Row(number=31, status="withdrawn"),
        )
    )
    asyncio.run(_supersede(postgis_url, (1, 2), (2, 3), (3, 4), (11, 12)))

    command.upgrade(alembic_config, "0025")
    lineages = asyncio.run(_fetch_lineages(postgis_url))
    command.downgrade(alembic_config, "0024")
    _delete_reports(postgis_url)

    expected = {1: 1, 2: 1, 3: 1, 4: 1, 11: 11, 12: 11, 21: 21, 31: 31}
    assert lineages == {
        _report_id(number): _report_id(root) for number, root in expected.items()
    }


def test_migration_0025_refuses_a_later_revision_that_supersedes_nothing(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0024")
    asyncio.run(_insert(postgis_url, _Row(number=41, revision=2)))

    with pytest.raises(IntegrityError, match="lineage_root_is_first_revision"):
        command.upgrade(alembic_config, "0025")
    lineages = asyncio.run(_fetch_lineages(postgis_url))
    _delete_reports(postgis_url)

    # The failed upgrade rolled back: no lineage column, still at 0024.
    assert lineages == {}


@pytest.mark.parametrize(
    ("offending", "rows"),
    [
        # Revision 2 whose predecessor link was lost (lineage set by hand).
        (52, (_Row(number=51, lineage=51), _Row(number=52, revision=2, lineage=51))),
        # Revision 1 that claims to supersede another report.
        (54, (_Row(number=53, lineage=53), _Row(number=54, supersedes=53, lineage=54))),
    ],
    ids=["later-revision-without-predecessor", "first-revision-with-predecessor"],
)
def test_migration_0026_pre_check_lists_the_offending_reports(
    alembic_config: Config, postgis_url: str, offending: int, rows: tuple[_Row, ...]
) -> None:
    command.upgrade(alembic_config, "0025")
    asyncio.run(_insert(postgis_url, *rows))

    with pytest.raises(DBAPIError, match=_report_id(offending)):
        command.upgrade(alembic_config, "0026")
    _delete_reports(postgis_url)


def test_migration_0026_adds_revision_check_and_queue_indexes_reversibly(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "0025")
    asyncio.run(
        _insert(
            postgis_url,
            _Row(number=61, lineage=61),
            _Row(number=62, revision=2, supersedes=61, lineage=61),
        )
    )
    orphan = _Row(number=63, revision=2, lineage=61)

    command.upgrade(alembic_config, "0026")
    indexes = asyncio.run(_fetch_index_names(postgis_url))
    with pytest.raises(IntegrityError, match="first_revision_supersedes_nothing"):
        asyncio.run(_insert(postgis_url, orphan))
    command.downgrade(alembic_config, "0025")
    downgraded_indexes = asyncio.run(_fetch_index_names(postgis_url))
    asyncio.run(_insert(postgis_url, orphan))
    _delete_reports(postgis_url)

    new_indexes = {"ix_reports_triage_gin", "ix_media_assets_completed_created_at_id"}
    assert new_indexes <= indexes
    assert not new_indexes & downgraded_indexes


async def _fetch_index_names(database_url: str) -> set[str]:
    """Return the names of every index in the public schema."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            result = await connection.execute(
                text("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'")
            )
            return set(result.scalars().all())
    finally:
        await engine.dispose()
