"""Alembic migration round trips, drift check and history shape on real PostGIS.

Alembic runs in-process through ``alembic.command`` with the container URL passed as
``-x database_url=...``, exactly as a developer would pass it on the command line.
The tests are plain ``def`` functions on purpose: ``migrations/env.py`` drives its own
event loop with ``asyncio.run``, which cannot start inside a running pytest-asyncio
loop.

Every test leaves the session database empty (no application tables, no
``alembic_version``) because the platform integration tests create the outbox table
themselves and would collide with a migrated schema.
"""

import asyncio
import io
from argparse import Namespace
from collections.abc import Iterator
from pathlib import Path
from typing import Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Connection, inspect, text
from sqlalchemy.ext.asyncio import create_async_engine

pytestmark = pytest.mark.integration

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[3]
ALEMBIC_INI: Final = REPOSITORY_ROOT / "alembic.ini"

VERSION_TABLE: Final = "alembic_version"
# Tables the PostGIS image creates in the public schema; they are not ours.
POSTGIS_TABLES: Final = frozenset({"spatial_ref_sys"})
APPLICATION_TABLES_AT_HEAD: Final = frozenset(
    {
        "outbox_messages",
        "places",
        "place_names",
        "hazard_types",
        "impact_metrics",
        "users",
        "organizations",
        "memberships",
        "idempotency_keys",
    }
)
EXTENSIONS: Final = frozenset({"postgis", "pg_trgm", "unaccent"})


def _read_public_tables(connection: Connection) -> set[str]:
    """Return the table names in the public schema."""
    return set(inspect(connection).get_table_names(schema="public"))


async def _fetch_public_tables(database_url: str) -> set[str]:
    """Connect once and list the public tables."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            return await connection.run_sync(_read_public_tables)
    finally:
        await engine.dispose()


async def _fetch_extensions(database_url: str) -> set[str]:
    """Connect once and list the installed extensions."""
    engine = create_async_engine(database_url)
    try:
        async with engine.connect() as connection:
            result = await connection.execute(text("SELECT extname FROM pg_extension"))
            return set(result.scalars().all())
    finally:
        await engine.dispose()


async def _execute(database_url: str, statement: str) -> None:
    """Run one fixed DDL statement in its own transaction."""
    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as connection:
            await connection.execute(text(statement))
    finally:
        await engine.dispose()


def _application_tables(database_url: str) -> set[str]:
    """Return every public table that is neither PostGIS's nor Alembic's."""
    tables = asyncio.run(_fetch_public_tables(database_url))
    return tables - POSTGIS_TABLES - {VERSION_TABLE}


def _build_config(
    database_url: str, output_buffer: io.StringIO | None = None
) -> Config:
    """Return an Alembic config for ``alembic.ini`` aimed at ``database_url``."""
    config = Config(
        ALEMBIC_INI,
        cmd_opts=Namespace(x=[f"database_url={database_url}"]),
        output_buffer=output_buffer,
    )
    # env.py would otherwise call fileConfig and replace pytest's log handlers.
    config.attributes["configure_logger"] = False
    return config


@pytest.fixture
def alembic_config(postgis_url: str) -> Iterator[Config]:
    """Yield a config on the empty session database and empty it again afterwards."""
    config = _build_config(postgis_url)

    yield config

    command.downgrade(config, "base")
    # downgrade base only empties the version table; drop it so the database is
    # exactly as empty as the platform tests expect.
    asyncio.run(_execute(postgis_url, f"DROP TABLE IF EXISTS {VERSION_TABLE}"))


def test_migrations_upgrade_head_downgrade_base_leaves_empty_schema(
    alembic_config: Config, postgis_url: str
) -> None:
    assert _application_tables(postgis_url) == set()

    command.upgrade(alembic_config, "head")
    tables_at_head = _application_tables(postgis_url)
    extensions_at_head = asyncio.run(_fetch_extensions(postgis_url))
    command.downgrade(alembic_config, "base")
    tables_at_base = _application_tables(postgis_url)

    assert tables_at_head == APPLICATION_TABLES_AT_HEAD
    assert extensions_at_head >= EXTENSIONS
    assert tables_at_base == set()


def test_migrations_upgrade_twice_is_idempotent_after_downgrade(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    command.upgrade(alembic_config, "head")

    assert _application_tables(postgis_url) == APPLICATION_TABLES_AT_HEAD


def test_alembic_check_reports_no_drift_at_head(alembic_config: Config) -> None:
    command.upgrade(alembic_config, "head")

    # Raises AutogenerateDiffsDetected if the models and the migrations disagree.
    command.check(alembic_config)


def test_alembic_check_with_column_altered_by_hand_reports_drift(
    alembic_config: Config, postgis_url: str
) -> None:
    command.upgrade(alembic_config, "head")
    # A change downgrade still undoes (it drops the whole table), so the fixture's
    # teardown keeps working.
    asyncio.run(
        _execute(
            postgis_url,
            "ALTER TABLE outbox_messages ALTER COLUMN last_error SET NOT NULL",
        )
    )

    with pytest.raises(AutogenerateDiffsDetected, match="last_error"):
        command.check(alembic_config)


def test_migrations_offline_mode_renders_outbox_sql_without_connecting(
    postgis_url: str,
) -> None:
    output = io.StringIO()
    config = _build_config(postgis_url, output_buffer=output)

    command.upgrade(config, "head", sql=True)

    rendered = output.getvalue()
    assert "CREATE EXTENSION IF NOT EXISTS postgis" in rendered
    assert "CREATE TABLE outbox_messages" in rendered
    assert _application_tables(postgis_url) == set()


def test_migration_history_is_linear() -> None:
    script = ScriptDirectory.from_config(Config(ALEMBIC_INI))

    revisions = list(script.walk_revisions())

    assert len(script.get_heads()) == 1
    assert len(script.get_bases()) == 1
    assert all(
        revision.down_revision is None or isinstance(revision.down_revision, str)
        for revision in revisions
    )
    assert all(not revision.branch_labels for revision in revisions)
