"""Value objects of the ``audit`` bounded context.

An audit entry holds **identifiers, codes and digests only**. The action is a routing
code, the target is a type code and an id, and every payload is reduced to a SHA-256
digest, so no free text (a report description, a citation, a reason) is ever copied
into the audit log, which is kept longer than any record it describes.

Patterns: Value Object.
"""

import hashlib
import re
from typing import Annotated, Final, Literal

from pydantic import BaseModel, ConfigDict, StringConstraints

from yakhnama.shared_kernel.ids import EntityId
from yakhnama.shared_kernel.text import safe_text

AUDIT_ACTION_PATTERN = r"^[a-z][a-z0-9_.]{1,63}$"

AuditAction = Annotated[str, StringConstraints(pattern=AUDIT_ACTION_PATTERN)]
"""What happened, 2 to 64 of ``a-z 0-9 _ .``, starting with a letter.

Normally the ``event_type`` of the recorded domain event, for example
``reports.report_submitted``.
"""

TARGET_TYPE_MAX_LENGTH = 64
TARGET_TYPE_PATTERN = r"^[a-z][a-z0-9_]*$"

TargetType = Annotated[
    str,
    StringConstraints(
        min_length=1, max_length=TARGET_TYPE_MAX_LENGTH, pattern=TARGET_TYPE_PATTERN
    ),
]
"""Snake-case type of the audited aggregate, for example ``source`` or ``report``."""


class AuditTarget(BaseModel):
    """The aggregate an audit entry is about.

    Implements: Value Object.

    Attributes:
        target_type: Snake-case aggregate type, normally the event's
            ``aggregate_type``.
        target_id: The aggregate's id (UUIDv7).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    target_type: TargetType
    target_id: EntityId


DIGEST_PREFIX: Final = "sha256:"
DIGEST_PATTERN = r"^sha256:[0-9a-f]{64}$"
_DIGEST_REGEX = re.compile(DIGEST_PATTERN)

Digest = Annotated[str, StringConstraints(pattern=DIGEST_PATTERN)]
"""A SHA-256 digest written ``sha256:`` plus 64 lower-case hexadecimal digits.

Lower case only, so one digest has exactly one spelling and digests compare as
strings. The algorithm prefix leaves room to change algorithm without ambiguity.
"""


def compute_digest(data: bytes) -> str:
    """Return the ``Digest`` of ``data``.

    Args:
        data: The bytes to hash, for example a canonical JSON payload.

    Returns:
        ``"sha256:"`` followed by the lower-case hexadecimal SHA-256 of ``data``.
    """
    return f"{DIGEST_PREFIX}{hashlib.sha256(data).hexdigest()}"


def is_digest(value: str) -> bool:
    """Tell whether ``value`` is a well-formed ``Digest``.

    Args:
        value: A candidate such as ``"sha256:ab12..."``.

    Returns:
        ``True`` if it matches ``DIGEST_PATTERN``.
    """
    return _DIGEST_REGEX.fullmatch(value) is not None


class StateDigests(BaseModel):
    """Digests of an aggregate's state before and after one change.

    Either may be missing: a creation has no ``before``, and a subscriber that only
    sees the event may know neither.

    Implements: Value Object.

    Attributes:
        before: Digest of the state before the change, if known.
        after: Digest of the state after the change, if known.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    before: Digest | None = None
    after: Digest | None = None


NO_STATE_DIGESTS: Final = StateDigests()
"""Neither digest known; the default for ``from_domain_event``."""

REQUEST_ID_MAX_LENGTH = 128

RequestId = Annotated[str, *safe_text(REQUEST_ID_MAX_LENGTH)]
"""Correlation id of the HTTP request or task that caused the change, 1 to 128.

Generated by the platform (or a client's ``X-Request-ID``), never typed by a person,
but still held to the safe-text rules because a client can send any header value.
"""

ActorKind = Literal["user", "system"]
"""Who acted: a signed-in ``user`` (with an actor id) or the ``system``."""
