"""The Taskiq adapter of the kernel's ``TaskQueue`` port (ADR 0008).

``register_tasks`` registers one Taskiq task per name in ``TASK_NAMES`` on a broker.
Every registered task is the same thin runner: it rebuilds the ``ScheduledTask`` from
the broker message (payload from the keyword arguments, id and idempotency key from
the message) and hands it to the handler bound in a ``TaskHandlerRegistry``.
``TaskiqTaskQueue`` validates each ``enqueue`` into a ``ScheduledTask`` and sends it.

Wire format: the payload travels as keyword arguments in JSON (a UUID as its string);
the idempotency key travels as the message label ``IDEMPOTENCY_KEY_LABEL``; the task
id is the ``ScheduledTask.task_id``, generated by the broker's id generator (a hex
UUID4).

**Delays are not supported.** Neither broker in use can hold a message back (Taskiq's
``delay`` label is honoured only by brokers such as RabbitMQ), so ``enqueue`` refuses
``delay_seconds > 0`` with ``TaskDelayUnsupportedError`` instead of running the task
early. A delayed task needs a schedule source such as ``taskiq_redis``'s
``ListRedisScheduleSource`` read by the scheduler; that is an open question for the
first module that needs one.

Patterns: Adapter, Registry.
"""

from collections.abc import Awaitable, Callable, Mapping, Sequence
from typing import Any, Final
from uuid import UUID

import structlog
from pydantic import ValidationError as PydanticValidationError
from taskiq import AsyncBroker, AsyncTaskiqDecoratedTask, Context, TaskiqDepends
from taskiq.exceptions import SendTaskError
from taskiq.kicker import AsyncKicker
from taskiq.message import TaskiqMessage

from yakhnama.platform.tasks.errors import (
    TaskDelayUnsupportedError,
    TaskFailedError,
    TaskNotRegisteredError,
    TaskQueueUnavailableError,
)
from yakhnama.platform.tasks.handlers import TASK_NAMES, TaskHandlerRegistry
from yakhnama.platform.tasks.scheduled import TaskSchedule
from yakhnama.shared_kernel.tasks import ScheduledTask, TaskId, TaskPayloadValue

IDEMPOTENCY_KEY_LABEL: Final = "idempotency_key"
# Taskiq's own label for LabelScheduleSource; describes the task, not one message,
# so it is not copied onto the messages this adapter sends.
SCHEDULE_LABEL: Final = "schedule"

# A module-level marker rather than a call in the signature (Ruff B008); Taskiq
# resolves it to the running message's Context.
CONTEXT_DEPENDENCY: Final[Context] = TaskiqDepends()

type JsonPayloadValue = str | int | bool | None
# Any: the Taskiq task wraps the runner, whose keyword arguments are the payload.
type RegisteredTask = AsyncTaskiqDecoratedTask[..., Any]


class TaskRegistry:
    """The Taskiq tasks registered on one broker, by task name.

    Implements: Registry.
    """

    def __init__(self) -> None:
        """Create an empty registry."""
        self._tasks: dict[str, RegisteredTask] = {}

    def add(self, task: RegisteredTask) -> None:
        """Record ``task`` under its Taskiq task name.

        Args:
            task: A task registered on the broker.
        """
        self._tasks[task.task_name] = task

    def find(self, task_name: str) -> RegisteredTask:
        """Return the task registered as ``task_name``.

        Args:
            task_name: A validated ``TaskName``.

        Returns:
            The registered Taskiq task.

        Raises:
            TaskNotRegisteredError: If no task has that name.
        """
        task = self._tasks.get(task_name)
        if task is None:
            message = f"no task is registered as {task_name}"
            raise TaskNotRegisteredError(message, details={"task_name": task_name})
        return task

    def names(self) -> tuple[str, ...]:
        """Return the registered task names in registration order.

        Returns:
            The names.
        """
        return tuple(self._tasks)


def task_from_message(
    message: TaskiqMessage, payload: Mapping[str, object]
) -> ScheduledTask:
    """Rebuild the ``ScheduledTask`` a worker received.

    Args:
        message: The Taskiq message being executed.
        payload: Its keyword arguments.

    Returns:
        The task, with ``delay_seconds`` 0 because it is running now.

    Raises:
        pydantic.ValidationError: If the message breaks the payload contract (it
            was not sent by ``TaskiqTaskQueue``).
    """
    return ScheduledTask.model_validate(
        {
            "task_id": {"value": message.task_id},
            "task_name": message.task_name,
            "payload": dict(payload),
            "idempotency_key": message.labels.get(IDEMPOTENCY_KEY_LABEL),
        }
    )


async def execute_task(
    message: TaskiqMessage,
    payload: Mapping[str, object],
    handlers: TaskHandlerRegistry,
) -> None:
    """Run the bound handler for one received message.

    Args:
        message: The Taskiq message being executed.
        payload: Its keyword arguments.
        handlers: Where the composition root bound the handlers.

    Raises:
        TaskHandlerNotBoundError: If no handler is bound for the task.
        TaskFailedError: If the payload is invalid or the handler raised; the
            original error is logged by type as ``task_failed`` and deliberately
            not chained, because its message may quote data.
    """
    try:
        task = task_from_message(message, payload)
    except PydanticValidationError as error:
        _log_task_failed(message.task_name, message.task_id, error)
        failure = f"{message.task_name} received an invalid payload"
        raise TaskFailedError(
            failure, details={"task_name": message.task_name}
        ) from None
    handler = handlers.handler_for(task)
    try:
        await handler(task)
    # Handlers are module code; whatever they raise is logged by type and re-raised
    # as a TaskFailedError so the task is recorded as failed.
    except Exception as error:  # noqa: BLE001  # reason: logged by type and re-raised as TaskFailedError
        _log_task_failed(task.task_name, task.task_id.value, error)
        failure = f"{task.task_name} failed with {type(error).__name__}"
        raise TaskFailedError(
            failure,
            details={"task_name": task.task_name, "error_type": type(error).__name__},
        ) from None


def _log_task_failed(task_name: str, task_id: str, error: Exception) -> None:
    # Identifiers and the error type only; the error message may quote data
    # (AGENTS.md §5).
    structlog.get_logger(__name__).error(
        "task_failed",
        # "task", not "task_name": the log redaction treats keys ending in "name"
        # as personal data.
        task=task_name,
        task_id=task_id,
        error_type=type(error).__name__,
    )


def _runner(handlers: TaskHandlerRegistry) -> Callable[..., Awaitable[None]]:
    # ``_context`` is resolved by Taskiq's dependency injection; its leading
    # underscore cannot collide with a payload key, which must start with a letter.
    async def run(_context: Context = CONTEXT_DEPENDENCY, **payload: object) -> None:
        await execute_task(_context.message, payload, handlers)

    return run


def register_tasks(
    broker: AsyncBroker,
    handlers: TaskHandlerRegistry,
    schedules: Sequence[TaskSchedule] = (),
    task_names: Sequence[str] = TASK_NAMES,
) -> TaskRegistry:
    """Register one runner task per name on ``broker``.

    Args:
        broker: The broker the tasks run on.
        handlers: Looked up when a task runs, so handlers bound after this call are
            found.
        schedules: Periodic schedules, attached as ``schedule`` labels for the
            ``LabelScheduleSource``.
        task_names: The names to register.

    Returns:
        The registered tasks by name.
    """
    intervals = {
        schedule.task_name: schedule.interval_seconds for schedule in schedules
    }
    registry = TaskRegistry()
    for task_name in task_names:
        labels: dict[str, object] = {}
        if task_name in intervals:
            # The schedule id is the task name, so it is stable across restarts
            # and the scheduler tracks one interval per task.
            labels[SCHEDULE_LABEL] = [
                {"interval": intervals[task_name], "schedule_id": task_name}
            ]
        registry.add(
            broker.register_task(_runner(handlers), task_name=task_name, **labels)
        )
    return registry


def _json_payload(
    payload: Mapping[str, TaskPayloadValue],
) -> dict[str, JsonPayloadValue]:
    return {
        key: str(value) if isinstance(value, UUID) else value
        for key, value in payload.items()
    }


class TaskiqTaskQueue:
    """``TaskQueue`` over a Taskiq broker.

    Implements: Adapter.
    """

    def __init__(self, broker: AsyncBroker, registry: TaskRegistry) -> None:
        """Create the queue.

        Args:
            broker: Where tasks are sent; its id generator assigns task ids.
            registry: The tasks registered on ``broker``.
        """
        self._broker = broker
        self._registry = registry

    async def enqueue(
        self,
        task_name: str,
        payload: Mapping[str, object],
        *,
        idempotency_key: str | None = None,
        delay_seconds: int = 0,
    ) -> TaskId:
        """Send one task to the broker; see ``TaskQueue.enqueue``.

        Args:
            task_name: A registered task name.
            payload: Ids and non-personal scalars.
            idempotency_key: Sent as the ``idempotency_key`` label.
            delay_seconds: Must be 0; see the module docstring.

        Returns:
            The id the task will run under.

        Raises:
            pydantic.ValidationError: If the arguments break the ``ScheduledTask``
                contract.
            TaskNotRegisteredError: If no task is registered as ``task_name``.
            TaskDelayUnsupportedError: If ``delay_seconds`` is positive.
            TaskQueueUnavailableError: If the broker could not take the task.
        """
        task = ScheduledTask.model_validate(
            {
                "task_id": {"value": self._broker.id_generator()},
                "task_name": task_name,
                "payload": dict(payload),
                "idempotency_key": idempotency_key,
                "delay_seconds": delay_seconds,
            }
        )
        registered = self._registry.find(task.task_name)
        if task.delay_seconds > 0:
            message = (
                f"{task.task_name}: this broker cannot delay delivery; "
                "enqueue with delay_seconds=0"
            )
            raise TaskDelayUnsupportedError(
                message, details={"task_name": task.task_name}
            )
        labels = {
            name: value
            for name, value in registered.labels.items()
            if name != SCHEDULE_LABEL
        }
        if task.idempotency_key is not None:
            labels[IDEMPOTENCY_KEY_LABEL] = task.idempotency_key
        kicker: AsyncKicker[..., Any] = AsyncKicker(
            registered.task_name, self._broker, labels
        ).with_task_id(task.task_id.value)
        try:
            await kicker.kiq(**_json_payload(task.payload))
        except SendTaskError as error:
            structlog.get_logger(__name__).error(
                "task_enqueue_failed",
                task=task.task_name,
                task_id=task.task_id.value,
            )
            message = f"the task queue did not accept {task.task_name}"
            raise TaskQueueUnavailableError(
                message, details={"task_name": task.task_name}
            ) from error
        return task.task_id
