"""Public facade of the ``identity`` module.

Other modules, the seed, the API and the composition root import only this file:
the ``Actor`` every policy evaluates, the roles, the policy protocol and the
composable policies, the ``require_allowed`` check, and the commands, queries, DTOs,
handlers and ports the API and the composition root wire together.

Patterns: Facade.
"""

from yakhnama.modules.identity.application.authorisation import (
    member_list_policy,
    organization_read_policy,
    require_allowed,
    self_policy,
)
from yakhnama.modules.identity.application.commands import (
    AddMember,
    ChangeMemberRole,
    CreateOrganization,
    EnsureUserFromPrincipal,
    GrantRole,
    ReinstateUser,
    RemoveMember,
    RenameOrganization,
    RenameSelf,
    RevokeRole,
    SuspendUser,
)
from yakhnama.modules.identity.application.dto import (
    MeDetail,
    MembershipSummary,
    MemberSummary,
    OrganizationDetail,
    OrganizationSummary,
    UserDetail,
)
from yakhnama.modules.identity.application.handlers import (
    AddMemberHandler,
    ChangeMemberRoleHandler,
    CreateOrganizationHandler,
    EnsureUserFromPrincipalHandler,
    GrantRoleHandler,
    ReinstateUserHandler,
    RemoveMemberHandler,
    RenameOrganizationHandler,
    RenameSelfHandler,
    RevokeRoleHandler,
    SuspendUserHandler,
)
from yakhnama.modules.identity.application.ports import (
    IdentityQueryService,
    IdentityUnitOfWork,
    IdentityUnitOfWorkFactory,
)
from yakhnama.modules.identity.application.queries import (
    GetMe,
    GetOrganization,
    ListOrganizationMembers,
)
from yakhnama.modules.identity.domain.policies import (
    ActorPolicy,
    AllOf,
    AnyOf,
    AuthorisationPolicy,
    CanManageOrganization,
    CanManageReferenceData,
    CanModerate,
    CanReadVerifiedData,
    HasRole,
    IsAdmin,
    IsAuthenticated,
    IsMemberOf,
    IsModerator,
    IsOrgAdminOf,
    IsSelf,
    Not,
    all_of,
    any_of,
)
from yakhnama.modules.identity.domain.value_objects import (
    Actor,
    ExternalIdentity,
    OrganizationRole,
    OrganizationStatus,
    OrganizationType,
    Role,
    UserStatus,
)

__all__ = [
    "Actor",
    "ActorPolicy",
    "AddMember",
    "AddMemberHandler",
    "AllOf",
    "AnyOf",
    "AuthorisationPolicy",
    "CanManageOrganization",
    "CanManageReferenceData",
    "CanModerate",
    "CanReadVerifiedData",
    "ChangeMemberRole",
    "ChangeMemberRoleHandler",
    "CreateOrganization",
    "CreateOrganizationHandler",
    "EnsureUserFromPrincipal",
    "EnsureUserFromPrincipalHandler",
    "ExternalIdentity",
    "GetMe",
    "GetOrganization",
    "GrantRole",
    "GrantRoleHandler",
    "HasRole",
    "IdentityQueryService",
    "IdentityUnitOfWork",
    "IdentityUnitOfWorkFactory",
    "IsAdmin",
    "IsAuthenticated",
    "IsMemberOf",
    "IsModerator",
    "IsOrgAdminOf",
    "IsSelf",
    "ListOrganizationMembers",
    "MeDetail",
    "MemberSummary",
    "MembershipSummary",
    "Not",
    "OrganizationDetail",
    "OrganizationRole",
    "OrganizationStatus",
    "OrganizationSummary",
    "OrganizationType",
    "ReinstateUser",
    "ReinstateUserHandler",
    "RemoveMember",
    "RemoveMemberHandler",
    "RenameOrganization",
    "RenameOrganizationHandler",
    "RenameSelf",
    "RenameSelfHandler",
    "RevokeRole",
    "RevokeRoleHandler",
    "Role",
    "SuspendUser",
    "SuspendUserHandler",
    "UserDetail",
    "UserStatus",
    "all_of",
    "any_of",
    "member_list_policy",
    "organization_read_policy",
    "require_allowed",
    "self_policy",
]
